[package]
name = "pbrtrs"
version = "0.1.0"
authors = ["Christopher Fu <chrisf1337@gmail.com>"]

[dependencies]
nalgebra = "*"
num-traits = "*"

[dev-dependencies]
pretty_assertions = "*"

[features]
default = []
float_as_f64 = []
